### ISSUE TITLE
pkg_resources.DistributionNotFound: Click

### ISSUE THREAD

**Issue by kylemcdonald** [HalfdanJ/ofx#1]
```
kyle$ pip install ofx
Downloading/unpacking ofx
  Downloading ofx-0.1.tar.gz
  Running setup.py (path:/private/var/folders/18/0s6nty6s7x3c8b5x57fp4czw0000gn/T/pip_build_kyle/ofx/setup.py) egg_info for package ofx

Downloading/unpacking Click (from ofx)
  Downloading click-3.3-py2.py3-none-any.whl (58kB): 58kB downloaded
Requirement already satisfied (use --upgrade to upgrade): sh in /usr/local/lib/python2.7/site-packages (from ofx)
Downloading/unpacking simplejson (from ofx)
  Downloading simplejson-3.6.5.tar.gz (73kB): 73kB downloaded
  Running setup.py (path:/private/var/folders/18/0s6nty6s7x3c8b5x57fp4czw0000gn/T/pip_build_kyle/simplejson/setup.py) egg_info for package simplejson

Installing collected packages: ofx, Click, simplejson
  Running setup.py install for ofx

    Installing ofx script to /usr/local/bin
  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c simplejson/_speedups.c -o build/temp.macosx-10.9-x86_64-2.7/simplejson/_speedups.o
    clang -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.9-x86_64-2.7/simplejson/_speedups.o -o build/lib.macosx-10.9-x86_64-2.7/simplejson/_speedups.so

Successfully installed ofx Click simplejson
Cleaning up...
kyle$ ofx --help
Traceback (most recent call last):
  File "/usr/local/bin/ofx", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Click
```

**Comment by lucasrangit** [comment]
I didn't get this error when I just tried it on Ubuntu 16.04.

```
$ pip install ofx
Collecting ofx
  Downloading https://files.pythonhosted.org/packages/a5/a5/1dd8cdde3c7d94766827a53d697db985d79091db950259ad3a5956f0f41d/ofx-0.1.tar.gz
Collecting Click (from ofx)
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |################################| 71kB 1.1MB/s 
Collecting sh (from ofx)
  Downloading https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
Collecting simplejson (from ofx)
  Downloading https://files.pythonhosted.org/packages/e3/24/c35fb1c1c315fc0fffe61ea00d3f88e85469004713dab488dee4f35b0aff/simplejson-3.16.0.tar.gz (81kB)
    100% |################################| 81kB 1.4MB/s 
Building wheels for collected packages: ofx, simplejson
  Running setup.py bdist_wheel for ofx ... done
  Stored in directory: /home/docker/.cache/pip/wheels/0e/82/6c/13bb542103142f6dc1e519fec49731c030ad1afcf3d81c5bcc
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /home/docker/.cache/pip/wheels/5d/1a/1e/0350bb3df3e74215cd91325344cc86c2c691f5306eb4d22c77
Successfully built ofx simplejson
Installing collected packages: Click, sh, simplejson, ofx
Successfully installed Click ofx sh simplejson
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ ofx --help
Usage: ofx [OPTIONS] COMMAND [ARGS]...

Options:
  --of-root TEXT     Overwrite path to of root
  --of-api-url TEXT  Overwrite url to ofxaddons.com api
  --help             Show this message and exit.

Commands:
  info       Returns info about an installed addon
  install    Installs an addon, leave out addon name to...
  list       List installed addons
  reinstall  Reinstalls an addon
  search     Search for an addon
  update     Update an addon
```
